version: '3'

services:
  db:
    container_name: db
    restart: always
    image: mariadb:10.9.4
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ${DB_PATH}/data:/var/lib/mysql
    networks:
      - app_network
  angular:
    container_name: client
    build: ${CLIENT_PATH}
    volumes:
      - ${CLIENT_PATH}/src:/application/src
      # dev-volume: delete when not in development env
      - ${CLIENT_PATH}:/application
    ports:
      - "3000:4200"
    depends_on:
      - server      
    networks:
      - app_network
  server:
    container_name: server
    build: ${SERVER_PATH}
    environment:
      DB_NAME: ${DB_NAME}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_URL: ${DB_URL}
    volumes:
      - ${SERVER_PATH}:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
    networks:
      - app_network


networks:
  app_network:
